version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: options_scalper
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader"]
      interval: 10s
      timeout: 5s
      retries: 5

  trading-bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://trader:${DB_PASSWORD}@postgres:5432/options_scalper
      BROKER_API_KEY: ${BROKER_API_KEY}
      BROKER_API_SECRET: ${BROKER_API_SECRET}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      WEBHOOK_URL: ${WEBHOOK_URL}
      INITIAL_CAPITAL: 100000
      TRADING_MODE: paper
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    command: python main.py --mode paper --capital 100000

volumes:
  postgres_data: