name: Daily Performance Report

on:
  schedule:
    # Run at 5:00 PM ET every weekday
    - cron: '0 21 * * 1-5'  # UTC time (adjust for daylight savings)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install psycopg2-binary pandas matplotlib seaborn
    
    - name: Generate daily report
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python scripts/generate_daily_report.py
    
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: daily-report-${{ github.run_id }}
        path: reports/
        retention-days: 90