name: ST0CKG

on:
  schedule:
    # Run at 9:20 AM ET every weekday
    # UTC times: 1:20 PM (summer/EDT) or 2:20 PM (winter/EST)
    - cron: '20 13 * * 1-5'  # 1:20 PM UTC (9:20 AM EDT)
  workflow_dispatch:  # Allow manual trigger

jobs:
  st0ckg-trading:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # 8 hour timeout
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt --verbose
    
    - name: Debug - Check code version
      run: |
        echo "Checking unified_market_data.py imports..."
        grep -n "OptionContractsRequest" src/unified_market_data.py || echo "OptionContractsRequest not found (good)"
        echo "Git commit:"
        git log --oneline -1
    
    - name: Check Database Schema
      id: check_db
      run: |
        echo "Checking if database migration is needed..."
        python3 << 'EOF'
        import os, sys
        from sqlalchemy import create_engine, text
        try:
            engine = create_engine(os.getenv('DATABASE_URL'))
            with engine.connect() as conn:
                # Quick test query
                conn.execute(text('SELECT bot_id, action FROM trades LIMIT 1'))
            print('Database schema is up to date')
            sys.exit(0)
        except Exception as e:
            print(f'Database migration needed: {e}')
            sys.exit(1)
        EOF
        echo "DB_OK=$?" >> $GITHUB_OUTPUT
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      continue-on-error: true
    
    - name: Run Database Migration
      if: steps.check_db.outputs.DB_OK != '0'
      run: |
        echo "Running database migration..."
        python src/force_fix_database.py || {
          echo "Force fix failed, attempting to recreate tables..."
          echo "yes" | python src/recreate_tables.py
        }
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    - name: Run ST0CKG Bot
      run: |
        echo "Starting ST0CKG Battle Lines Bot..."
        mkdir -p logs
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Python version:"
        python --version
        echo "Running bot..."
        python main_unified.py st0ckg || {
          echo "Bot failed with exit code $?"
          echo "Checking for error logs..."
          ls -la logs/
          if [ -f logs/startup_error.log ]; then
            echo "=== Startup Error Log ==="
            cat logs/startup_error.log
          fi
          if [ -f logs/import_error.log ]; then
            echo "=== Import Error Log ==="
            cat logs/import_error.log
          fi
          exit 1
        }
      env:
        PYTHONUNBUFFERED: 1
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ST0CKGKEY: ${{ secrets.STOCKGKEY }}
        ST0CKGSECRET: ${{ secrets.ST0CKGSECRET }}
        ALPACA_BASE_URL: ${{ secrets.ALPACA_BASE_URL }}
        CI: true  # This will make Redis use in-memory fallback
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: st0ckg-logs-${{ github.run_id }}
        path: logs/
        retention-days: 30
    
    - name: Send completion notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "ST0CKG trading session completed successfully"
        else
          echo "ST0CKG trading session failed or was cancelled"
        fi