name: ST0CKA

on:
  schedule:
    # Run at 9:20 AM ET every weekday
    # UTC times: 1:20 PM (summer/EDT) or 2:20 PM (winter/EST)
    - cron: '20 13 * * 1-5'  # 1:20 PM UTC (9:20 AM EDT)
  workflow_dispatch:  # Allow manual triggering

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # 8 hour timeout
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Debug - Check code version
      run: |
        echo "Checking unified_market_data.py imports..."
        grep -n "OptionContractsRequest" src/unified_market_data.py || echo "OptionContractsRequest not found (good)"
        echo "Git commit:"
        git log --oneline -1
        echo "Checking environment variables..."
        echo "STOCKA_KEY is: ${STOCKA_KEY:+set}"
        echo "APCA_API_KEY_ID is: ${APCA_API_KEY_ID:+set}"
      env:
        STOCKA_KEY: ${{ secrets.STOCKAKEY }}
        APCA_API_KEY_ID: ${{ secrets.STOCKAKEY }}
    
    - name: Run ST0CKA Trading Bot
      env:
        STOCKA_KEY: ${{ secrets.STOCKAKEY }}
        ST0CKA_SECRET: ${{ secrets.ST0CKASECRET }}
        APCA_API_KEY_ID: ${{ secrets.STOCKAKEY }}  # For UnifiedMarketData
        APCA_API_SECRET_KEY: ${{ secrets.ST0CKASECRET }}  # For UnifiedMarketData
        ALPACA_BASE_URL: ${{ secrets.ALPACA_BASE_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        mkdir -p logs
        python main_multi.py st0cka
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: st0cka-logs-${{ github.run_id }}
        path: logs/
        retention-days: 30