name: ST0CKA

on:
  schedule:
    # Run at 9:25 AM ET Monday-Friday (2:25 PM UTC)
    - cron: '25 14 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  trade:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Debug - Check code version
      run: |
        echo "Checking unified_market_data.py imports..."
        grep -n "OptionContractsRequest" src/unified_market_data.py || echo "OptionContractsRequest not found (good)"
        echo "Git commit:"
        git log --oneline -1
        echo "Checking environment variables..."
        echo "STOCKG_KEY is: ${STOCKG_KEY:+set}"
        echo "APCA_API_KEY_ID is: ${APCA_API_KEY_ID:+set}"
      env:
        STOCKG_KEY: ${{ secrets.STOCKG_KEY }}
        APCA_API_KEY_ID: ${{ secrets.STOCKG_KEY }}
    
    - name: Run ST0CKA Trading Bot
      env:
        STOCKG_KEY: ${{ secrets.STOCKG_KEY }}
        ST0CKG_SECRET: ${{ secrets.ST0CKG_SECRET }}
        STOCKA_KEY: ${{ secrets.STOCKG_KEY }}  # Use same key for now
        ST0CKA_SECRET: ${{ secrets.ST0CKG_SECRET }}  # Use same secret for now
        APCA_API_KEY_ID: ${{ secrets.STOCKG_KEY }}  # For UnifiedMarketData
        APCA_API_SECRET_KEY: ${{ secrets.ST0CKG_SECRET }}  # For UnifiedMarketData
        ALPACA_BASE_URL: ${{ secrets.ALPACA_BASE_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ST0CKA_TRADING_CAPITAL: ${{ secrets.ST0CKA_TRADING_CAPITAL }}
      run: |
        mkdir -p logs
        python main_multi.py st0cka
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: st0cka-logs-${{ github.run_id }}
        path: logs/
        retention-days: 30