name: Options Scalper Trading Bot

on:
  schedule:
    # Run at 9:25 AM ET every weekday (1:25 PM UTC during EDT, 2:25 PM UTC during EST)
    - cron: '25 13 * * 1-5'  # Adjust based on daylight savings
    - cron: '25 14 * * 1-5'  # Alternative schedule for EST
  workflow_dispatch:  # Allow manual trigger

jobs:
  trading-session:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # 8 hour timeout for full trading day
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure environment
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
        APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        echo "DATABASE_URL=$DATABASE_URL" > .env
        echo "APCA_API_KEY_ID=$APCA_API_KEY_ID" >> .env
        echo "APCA_API_SECRET_KEY=$APCA_API_SECRET_KEY" >> .env
        echo "EMAIL_USERNAME=$EMAIL_USERNAME" >> .env
        echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> .env
        echo "WEBHOOK_URL=$WEBHOOK_URL" >> .env
        echo "TRADING_CAPITAL=5000" >> .env
    
    - name: Run trading bot
      run: |
        echo "Starting FAST trading bot..."
        mkdir -p logs
        python main_fast.py
      env:
        PYTHONUNBUFFERED: 1
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
        APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
        TRADING_CAPITAL: 5000
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trading-logs-${{ github.run_id }}
        path: logs/
        retention-days: 30
    
    - name: Send completion notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "Trading session completed successfully"
        else
          echo "Trading session failed or was cancelled"
        fi